/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static conexion.BDSentencias.IDUs;
import controlador.ControladorGeneral;
import controlador.ControladorUsuario;
import controlador.ControladorVistaAyMU;
import controlador.ControladorVistaIngreso;
import java.awt.Dimension;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author jeron
 */
public class PrimeraPantalla extends javax.swing.JFrame {

    //SE DECLARAN LOS CONTROLADORES
    private ControladorUsuario refU;
    private ControladorGeneral ConG;
    private ControladorVistaAyMU AyMU;
    private ControladorVistaIngreso refCv;
    //SE DECLARA EL OBJETO ADMIN
    private Admin admin;
    //SE DECLARAN LAS VARIABLES
    private String usuario;
    private String pin;
    Dimension tam;

    //CONSTRUCTOR
    public PrimeraPantalla() {
        initComponents();
        //SE INICIALIZA EL CONTROLADOR USUARIO
        refU = new ControladorUsuario();
        //SE DIMENSIONA LA PANTALLA Y SE AGREGA EL ICONO
        Dimension aux = getToolkit().getScreenSize();
        this.setSize((int) aux.getWidth(), 573);

        URL url = getClass().getResource("/imagen/IconoRULF2.png");
        ImageIcon imag = new ImageIcon(url);
        setIconImage(imag.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBox = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        btnAgregarU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Unico de Libros Familiares");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName(""); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        PanelBox.setForeground(new java.awt.Color(255, 255, 255));
        PanelBox.setOpaque(false);

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");

        lblContraseña.setBackground(new java.awt.Color(255, 255, 255));
        lblContraseña.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña");

        txtUsuario.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setOpaque(false);

        btnIngresar.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/OK2.png"))); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtContraseña.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setToolTipText("");
        txtContraseña.setOpaque(false);

        tam = getSize();
        PanelBox.setLocation((tam.width/2)-(PanelBox.getWidth()/2), (tam.height/2)-(PanelBox.getHeight()/2));

        javax.swing.GroupLayout PanelBoxLayout = new javax.swing.GroupLayout(PanelBox);
        PanelBox.setLayout(PanelBoxLayout);
        PanelBoxLayout.setHorizontalGroup(
            PanelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBoxLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(PanelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBoxLayout.createSequentialGroup()
                        .addGroup(PanelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseña)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBoxLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        PanelBoxLayout.setVerticalGroup(
            PanelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBoxLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(PanelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(PanelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        btnAgregarU.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/NuevoUsuario.png"))); // NOI18N
        btnAgregarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(PanelBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAgregarU, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAgregarU, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        PanelBox.getAccessibleContext().setAccessibleParent(PanelBox);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUActionPerformed
        //CUANDO SE CLICKEA AGREGAR USUARIO
        //SE INCIALIZA EL CONTROLADOR AGREGAR Y MODIFICAR USUARIO
        AyMU = new ControladorVistaAyMU();
        //SE LLAMA AL METODO QUE ABRE LA PANTALLA AGREGAR Y MODIFICAR USUARIO
        AyMU.Start();
        //SE CIERRA LA PANTALLA PRINCIPAL
        this.setVisible(false);
    }//GEN-LAST:event_btnAgregarUActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        //SI SE CLICKEA EL BOTON INGRESAR
        //SE DECLARA UNA VARIABLE BOOLEANA
        boolean marca = false;
        //SE INICIALIZA EL CONTROLADOR GENERAL
        ConG = new ControladorGeneral();
        //SE INICIALIZA EL CONTROLADOR DE INGRESO
        refCv = new ControladorVistaIngreso();
        //SE INCIALIZAN LAS VARIABLES CON EL TEXTO ESCRITO EN LOS TXT DE LA PANTALLA
        usuario = txtUsuario.getText();
        pin = String.valueOf(txtContraseña.getPassword());
        //SE VERIFICA SI LOS CAMPOS DICEN USUARIO ADMIN CONTRASEÑA ADMIN
        if ((usuario.equals("Admin")) & (pin.equals("admin"))) {
            //SE INCIIALIZA EL OBJETO ADMIN
            admin = new Admin();
            //SE ABRE LA PANTALLA DE ADMINISTRADO
            admin.setVisible(true);

        } else {//SI NO SE ESCRIBIO EL USUARIO Y CONTRASEÑA ADMIN
            //SE VERIFICA QUE NO HAYA QUEDADO VACIO LOS CAMPOS USUARIO Y CONTRASEÑA
            if ((usuario.equals("")) & (pin.equals(""))) {//SI SE DETECTA QUE ESTAN VACIOS
                //SE INFORMA QUE NO DEBEN QUEDAR ESTOS DATOS VACIOS
                JOptionPane.showMessageDialog(this, "COLOQUE NOMBRE DE USUARIO Y CONTRASEÑA", "ERROR", 0);
            } else {//SI NO SE DETECA QUE ESTEN VACIOS LOS CAMPOS
                //SE LLAMA AL METODO PARA CARGAR LOS DATOS EN EL CONTROLADO DE USUARIO
                refU.IngresoManual(usuario, pin);
                //SE VERIFICA QUE EL USUARIO Y CONTRASEÑA SEAN CORRECTOS
                marca = refU.Comparacion1();
                if (marca == true) {//SI EL METODO TRAE COMO RESULTADO VERDADERO
                    //SE DECLARA VARIABLE QUE TOMA EL DATO ESCRITO EN EL TXT USUARIO 
                    String[] aux = {txtUsuario.getText()};
                    String[] respuesta = new String[1];
                    //SE LLAMA AL METODO PARA TRAER EL IDE DEL NOMBRE DE USUARIO TIPEADO
                    respuesta = ConG.mostrarFormulario(IDUs, aux);
                    //SE PASA EL RESULTADO DE STRING A LONG
                    Long id2 = Long.valueOf(respuesta[0]);
                    //SE LLAMA EL METODO PARA ABRIR PANTALLA INGRESO
                    refCv.Start(id2);
                    //SE CIERRA PANTALLA PRINICIPAL
                    this.setVisible(false);
                }

            }
        }


    }//GEN-LAST:event_btnIngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBox;
    private javax.swing.JButton btnAgregarU;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
